version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.lettuce:lettuce-core
    versions:
    - 6.1.0.RELEASE
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin.kapt
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: io.fabric8:kubernetes-client
    versions:
    - 5.0.1
    - 5.1.0
    - 5.1.1
    - 5.2.0
    - 5.2.1
