[core]
protocolVersion = 498

# Redis connection URI
redis = ""

# Kubernetes API address
kubernetes = "null"

# rabbitMq
rabbitMqHost = ""
rabbitMqPort = 5672
rabbitMqUsername = ""
rabbitMqPassword = ""
rabbitMqExchange = ""

[galaxy]
# Galaxy docker image
image = "registry.gitlab.com/oktw-network/galaxy"

# Kubernetes image pull secret
pullSecret = "gitlab"

    [galaxy.resource]
    # Container CPU require
    cpuRequire = "300Mi"

    # Container memory require
    memoryRequire = "800Mi"

    # Container CPU limit
    cpuLimit = "2"

    # Container memory limit
    memoryLimit = "2Gi"

    [galaxy.storage]
    # Kubernetes storage class
    storageClass = ""

    # Volume size
    size = "3Gi"
