[core]
protocolVersion = 485

# Redis connection URI
redis = ""

# Kubernetes API address
kubernetes = "null"

[galaxy]
# Galaxy docker image
image = "registry.gitlab.com/oktw-network/docker-galaxy:fabric"

# Kubernetes image pull secret
pullSecret = "gitlab"

    [resource]
    # Container CPU require
    cpuRequire = "300Mi"

    # Container memory require
    memoryRequire = "800Mi"

    # Container CPU limit
    cpuLimit = "2"

    # Container memory limit
    memoryLimit = "2Gi"

    [storage]
    # Kubernetes storage class
    storageClass = ""

    # Volume size
    size = "3Gi"
