name: build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: caches-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            caches-

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload-Artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: build/libs/

      - name: Copy build file
        run: cp build/libs/galaxy-proxy-1.0-SNAPSHOT.jar docker/plugins

      - name: Build the Docker image
        run: |
          docker build .
