name: Proxy CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

  docker-build:
    name: Docker build
    needs: build
    runs-on: ubuntu-latest
 
    steps:
    - name: Copy build file
      run: cp build/libs/galaxy-proxy-1.0-SNAPSHOT.jar docker/plugins
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

