name: build-latest

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
          architecture: x64

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload-Artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact
          path: build/libs/

      - name: Copy build file
        run: cp build/libs/galaxy-proxy-1.0-SNAPSHOT.jar docker/plugins

      - name: Build the Docker image and Publish to Registry
        run: |
          docker login docker.pkg.github.com -u "OKTW-Network" -p "${{ secrets.OKTW_PACKAGE }}"
          docker build . --file Dockerfile --tag galaxy-proxy
          docker tag galaxy-proxy docker.pkg.github.com/oktw-network/galaxy-proxy/galaxy-proxy:latest
          docker push docker.pkg.github.com/oktw-network/galaxy-proxy/galaxy-proxy:latest
